# Generated by Django 5.2.7 on 2025-11-13 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="course",
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
    ]
